apiVersion: v1
kind: Service
metadata:
  name: ps-app-service
  namespace: ps
spec:
  selector:
    app: ps-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
  